package seedu.address.ui.testutil;

import static org.junit.Assert.assertEquals;
import static seedu.address.ui.PersonCard.TAG_COLOR_STYLES;

import java.util.List;
import java.util.stream.Collectors;

import guitests.guihandles.DetailsPanelHandle;
import guitests.guihandles.PairCardHandle;
import guitests.guihandles.PersonCardHandle;
import guitests.guihandles.PersonListPanelHandle;
import guitests.guihandles.ResultDisplayHandle;
import seedu.address.model.pair.Pair;
import seedu.address.model.person.Person;
import seedu.address.ui.PersonCard;

/**
 * A set of assertion methods useful for writing GUI tests.
 */
public class GuiTestAssert {
    private static final String LABEL_DEFAULT_STYLE = "label";

    /**
     * Asserts that {@code actualCard} displays the same values as {@code expectedCard}.
     */
    public static void assertCardEquals(PersonCardHandle expectedCard, PersonCardHandle actualCard) {
        assertEquals(expectedCard.getId(), actualCard.getId());
        assertEquals(expectedCard.getName(), actualCard.getName());
        assertEquals(expectedCard.getTags(), actualCard.getTags());

        expectedCard.getTags().forEach(tag ->
            assertEquals(expectedCard.getTagStyleClasses(tag), actualCard.getTagStyleClasses(tag)));
    }

    /**
     * Asserts that {@code actualCard} displays the details of {@code expectedPerson}.
     */
    public static void assertCardDisplaysPerson(Person expectedPerson, PersonCardHandle actualCard) {
        assertEquals(expectedPerson.getName().fullName, actualCard.getName());

        assertTagsEqual(expectedPerson, actualCard);
    }

    /**
     * Asserts that {@code actualCard} displays the details of {@code expectedPair}.
     */
    public static void assertCardDisplaysPair(Pair expectedPair, PairCardHandle actualCard) {
        assertEquals(expectedPair.getPairName(), actualCard.getName());

        assertTagsEqual(expectedPair, actualCard);
    }

    /**
     * Asserts that {@code actualPanel} displays the details of {@code expectedPerson}.
     */
    public static void assertPanelDisplaysDetails(Person expectedPerson, DetailsPanelHandle actualBrowser) {
        assertEquals(expectedPerson.getName().fullName, actualBrowser.getName());
        assertEquals(expectedPerson.getPhone().value, actualBrowser.getPhone());
        assertEquals(expectedPerson.getEmail().value, actualBrowser.getEmail());
        assertEquals(expectedPerson.getAddress().value, actualBrowser.getAddress());
        assertEquals(expectedPerson.getStatus().value, actualBrowser.getStatus());
        assertEquals(expectedPerson.getRole().value, actualBrowser.getRole());
        assertEquals(expectedPerson.getSubject().value, actualBrowser.getSubject());
        assertEquals(expectedPerson.getLevel().value, actualBrowser.getLevel());
        assertEquals("$" + expectedPerson.getPrice().value + " / hr", actualBrowser.getPrice());
        assertEquals(expectedPerson.getRemark().value, actualBrowser.getRemark());
        assertEquals(Double.toString(expectedPerson.getRate().getDisplayedValue()), actualBrowser.getRate());
        assertEquals(Integer.toString(expectedPerson.getRate().getCount()), actualBrowser.getRateCount());
    }

    /**
     * Returns the color style for {@code tagName}'s label. The tag's color is determined by looking up the color
     * in {@code PersonCard#TAG_COLOR_STYLES}, using an index generated by the has code of the tag's content.
     *
     * @see PersonCard#getTagColorStyleFor(String)
     */
    private static String getTagColorStyleFor(String tagName) {
        return TAG_COLOR_STYLES[Math.abs(tagName.hashCode()) % TAG_COLOR_STYLES.length];
    }

    /**
     * Asserts that the tags in {@code actualCard} matches all the tags in {@code expectedPerson} with the correct
     * color.
     */
    private static void assertTagsEqual(Person expectedPerson, PersonCardHandle actualCard) {
        List<String> expectedTags = expectedPerson.getTags().stream()
                .map(tag -> tag.tagName).collect(Collectors.toList());
        assertEquals(expectedTags, actualCard.getTags());
        /*expectedTags.forEach(tag ->
            assertEquals(Arrays.asList(LABEL_DEFAULT_STYLE, getTagColorStyleFor(tag)),
                    actualCard.getTagStyleClasses(tag)));*/
    }

    /**
     * Asserts that the tags in {@code actualCard} matches all the tags in {@code expectedPair} with the correct
     * color.
     */
    private static void assertTagsEqual(Pair expectedPair, PairCardHandle actualCard) {
        List<String> expectedTags = expectedPair.getTags().stream()
                .map(tag -> tag.tagName).collect(Collectors.toList());
        assertEquals(expectedTags, actualCard.getTags());
        /*expectedTags.forEach(tag ->
            assertEquals(Arrays.asList(LABEL_DEFAULT_STYLE, getTagColorStyleFor(tag)),
                    actualCard.getTagStyleClasses(tag)));*/
    }

    /**
     * Asserts that the list in {@code personListPanelHandle} displays the details of {@code persons} correctly and
     * in the correct order.
     */
    public static void assertListMatching(PersonListPanelHandle personListPanelHandle, Person... persons) {
        for (int i = 0; i < persons.length; i++) {
            assertCardDisplaysPerson(persons[i], personListPanelHandle.getPersonCardHandle(i));
        }
    }

    /**
     * Asserts that the list in {@code personListPanelHandle} displays the details of {@code persons} correctly and
     * in the correct order.
     */
    public static void assertListMatching(PersonListPanelHandle personListPanelHandle, List<Person> persons) {
        assertListMatching(personListPanelHandle, persons.toArray(new Person[0]));
    }

    /**
     * Asserts the size of the list in {@code personListPanelHandle} equals to {@code size}.
     */
    public static void assertListSize(PersonListPanelHandle personListPanelHandle, int size) {
        int numberOfPeople = personListPanelHandle.getListSize();
        assertEquals(size, numberOfPeople);
    }

    /**
     * Asserts the message shown in {@code resultDisplayHandle} equals to {@code expected}.
     */
    public static void assertResultMessage(ResultDisplayHandle resultDisplayHandle, String expected) {
        assertEquals(expected, resultDisplayHandle.getText());
    }
}
