= Wang Zi - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: STUtor - v1.5

---

== Overview

STUtor -v1.5 is a desktop address book targeting tutor coordinators
to help them _matching_ and _managing_ a large database of tutors and students. +
The user interacts with it using a CLI, and it has a GUI created with JavaFX.
It is written in Java, and has about 25 kLoC.

== Summary of contributions

* *Major enhancement*:
added *the ability to match/unmatch a student and a tutor*
** What it does:
allows the user to choose a student and a tutor to match, or to choose a currently matched pair and unmatch it.
** Justification:
This feature makes the accounting process of matching easier.
Matching/Unmatching is done automatically after the target student and tutor is provided by the user,
therefore saving time in marking individual tutor or student and updating their status.
** Highlights:
The new Pair class interact heavily with the existing Person and Tag class,
and careful thinking is required to ensure full exploitation of the existing classes
without increasing the coupling.


* *Minor enhancement*:
Added the ability to accept case-insensitive input, as well as shortcuts,
for filling in subject, level, status and role.
On top of that, standardize storage format and display to follow <<proper-case, proper case>>.

* *Code contributed*: [https://github.com/CS2103JAN2018-W11-B1/main/blob/master/collated/functional/alexawangzi.md[Functional code]] [https://github.com/CS2103JAN2018-W11-B1/main/blob/master/collated/test/alexawangzi.md[Test code]]

* *Other contributions*:

** Project management:
** Enhancements to existing features:
** Documentation:
** Community:
** Tools:




== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=match]

include::../UserGuide.adoc[tag=unmatch]

include::../UserGuide.adoc[tag=commandsummary]

include::../UserGuide.adoc[tag=prefixshorcut]

include::../UserGuide.adoc[tag=faq]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=matchunmatch]

include::../DeveloperGuide.adoc[tag=fillingshortcut]

include::../DeveloperGuide.adoc[tag=caseinsensitiveinput]

[appendix]
== Glossary

[[proper-case]] Proper case::
Proper case is any text that is written with each of the first letters of every word being capitalized.
For example, "This Is An Example Of Proper Case."
